#!/usr/bin/env python

import json
import sys

if __name__ == '__main__':
    keys = sys.argv[1:]
    try:
        obj = json.load(sys.stdin)
        for key in keys:
            try:
                if isinstance(obj, list):
                    obj = obj[int(key)]
                elif isinstance(obj, dict):
                    obj = obj[key]
                else:
                    sys.stderr.write("WTF is this? {0}".format(obj))
            except KeyError:
                sys.stderr.write("Key '{0}' does not exist\n".format(key))
                sys.exit(1)
        if isinstance(obj, basestring):
            print obj
        else:
            json.dump(obj, sys.stdout, indent=4)
    except KeyboardInterrupt:
        pass
